[package]
name = "gdk"
version = "0.1.1"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GDK library"
repository = "https://github.com/gtk-rs/gdk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gdk/"

readme = "README.md"

keywords = ["gdk", "gtk", "gtk-rs", "gnome", "GUI"]

[lib]
name = "gdk"

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/sys" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }
libc = "0.1"
